name: dson
version: 0.1.4+1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_commons: '>=0.0.3 <0.0.4'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
