name: dson
version: 0.1.6
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=1.8.0'
dependencies:
  drails_commons: '^0.0.5'
#    path: ../drails_commons
  reflectable: '^0.1.0'
dev_dependencies:
  unittest: '>=0.12.0'
transformers:
- reflectable:
    entry_points:
      - lib/serializer.dart
