name: dson
version: 0.3.0+1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=1.8.0'
dependencies:
  drails_commons: '>=0.0.6 <0.1.0'
  reflectable: ^0.5.1
#  drails_commons:
#    path: ../drails_commons
#  reflectable:
#    path: ../reflectable/reflectable
dev_dependencies:
  test: '>=0.12.0'
transformers:
- reflectable:
    $include: ["test/*.dart", "test/serializer/*.dart", "test/deserializer/*.dart"]
    entry_points:
      - test/serializer/cyclic_reference_test.dart
      - test/serializer/exclude_test.dart
      - test/serializer/simple_test.dart
      - test/deserializer/deserializer_test.dart
